<?php

require_once 'auth.php';
require_login('driver');
require_once 'db.php';

// Fetch all active stations
$stmt = $pdo->prepare("
    SELECT s.station_id, s.station_name, s.address, s.latitude, s.longitude, 
           s.plug_type, s.charging_speed, s.pricing
    FROM tbl_stations s
    WHERE s.status='active'
");
$stmt->execute();
$all_stations = $stmt->fetchAll(PDO::FETCH_ASSOC);
$stations_json = json_encode($all_stations);

// Driver info from session (robust)
$driver_name = $_SESSION['user']['name'] ?? $_SESSION['name'] ?? 'Driver';
$driver_id = $_SESSION['user']['id'] ?? $_SESSION['driver_id'] ?? null;
if (!$driver_id && !empty($_SESSION['user']['email'])) {
    // fallback: try to find driver by email
    $stmt = $pdo->prepare("SELECT driver_id, name FROM tbl_drivers WHERE email = ? LIMIT 1");
    $stmt->execute([$_SESSION['user']['email']]);
    $r = $stmt->fetch(PDO::FETCH_ASSOC);
    if ($r) {
        $driver_id = $r['driver_id'];
        $driver_name = $r['name'] ?? $driver_name;
    }
}

// If driver_id still missing, attempt alternate session keys - harmless if present
if (!$driver_id && isset($_SESSION['driver_id'])) $driver_id = $_SESSION['driver_id'];

// Fetch driver's bookings (if we have driver_id)
$bookings = [];
if ($driver_id) {
    $stmt = $pdo->prepare("
    SELECT b.*, s.station_name, s.pricing
    FROM tbl_bookings b
    LEFT JOIN tbl_stations s ON b.station_id = s.station_id
    WHERE b.user_id = ?
    ORDER BY b.booking_id DESC
");
$stmt->execute([$driver_id]);
$bookings = $stmt->fetchAll(PDO::FETCH_ASSOC);

}

include 'partials/header.php';
?>
<!-- Flatpickr CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<!-- Flatpickr JS -->
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<!-- Hero Section -->
<section class="hero-section">
    <div class="hero-overlay"></div>
    <div class="container text-center hero-content">
        <h1 class="headline display-5 fw-bold">
            WattWay — 
            <span style="background:linear-gradient(90deg,var(--accent1),var(--accent2));
                         -webkit-background-clip:text;
                         -webkit-text-fill-color:transparent;">
                Welcome, <?php echo htmlspecialchars($driver_name); ?>!
            </span>
        </h1>
        <p class="hero-sub">Find electric vehicle charging stations near you quickly and easily.</p>
        <button class="btn btn-outline-primary mt-3" id="locateBtn">
            <i class="bi bi-geo-alt-fill"></i> Use My Location
        </button>
        <button class="btn btn-secondary mt-3 ms-2" id="clearLocationBtn" style="display:none;">
            <i class="bi bi-x-circle"></i> Clear Location Filter
        </button>
    </div>
    <div class="floating-circles"><span></span><span></span><span></span><span></span><span></span></div>
</section>

<div class="container my-5">

    <div class="row">
        <div class="col-lg-8">
            <!-- 🔎 Filters -->
            <div class="row g-3 mb-4">
                <div class="col-md-6">
                    <input type="text" id="searchStation" class="form-control form-control-lg" placeholder="Search by name or address...">
                </div>
                <div class="col-md-3">
                    <select id="filterPlug" class="form-select form-select-lg">
                        <option value="">All Plug Types</option>
                        <option value="Type1">Type1</option>
                        <option value="Type2">Type2</option>
                        <option value="CCS">CCS</option>
                        <option value="CHAdeMO">CHAdeMO</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <select id="filterSpeed" class="form-select form-select-lg">
                        <option value="">All Speeds</option>
                        <option value="Slow">Slow</option>
                        <option value="Fast">Fast</option>
                        <option value="Rapid">Rapid</option>
                    </select>
                </div>
                <div class="col-md-3 mt-2">
                    <input type="number" id="filterPrice" class="form-control form-control-lg" placeholder="Max Price (₹)">
                </div>
                <div class="col-md-3 mt-2">
                    <button id="applyFilters" class="btn btn-brand w-100 btn-lg">Apply Filters</button>
                </div>
            </div>

  <!-- Station Cards -->
            <div class="row" id="stationCards">
                <!-- Station cards generated by JS -->
            </div>
        </div>


          

        <div class="col-lg-4">
            <!-- Bookings / Payments panel -->
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">Your Bookings</h5>
                    <?php if (!$driver_id): ?>
                        <div class="alert alert-warning">Driver ID not found in session; bookings cannot be shown.</div>
                    <?php elseif (empty($bookings)): ?>
                        <p class="small text-muted">No bookings yet.</p>
                    <?php else: ?>
                        <div class="list-group">
                            <?php foreach ($bookings as $b): ?>
                                <div class="list-group-item">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h6 class="mb-1"><?php echo htmlspecialchars($b['station_name'] ?? 'Station'); ?></h6>
                                        <small>#<?php echo $b['booking_id']; ?></small>
                                    </div>
                                    <p class="mb-1 small">
                                        Date: <?php echo htmlspecialchars($b['booking_date'] ?? $b['visit_date'] ?? '-'); ?><br>
                                        Time: <?php echo htmlspecialchars($b['visit_time'] ?? '-'); ?><br>
                                        Price: ₹<?php echo htmlspecialchars($b['pricing'] ?? '0'); ?>
                                    </p>
                                    <div class="d-flex gap-2">
                                        <?php if (($b['payment_status'] ?? '') === 'Paid'): ?>
                                            <span class="badge bg-success align-self-center">Paid</span>
                                            <small class="text-muted align-self-center">OTP: <?php echo htmlspecialchars($b['otp'] ?? '-'); ?></small>
                                        <?php else: ?>
                                            <a href="API/booking_payment.php?booking_id=<?php echo urlencode($b['booking_id']); ?>" target="_blank" class="btn btn-sm btn-primary">Pay Now</a>
                                            <span class="badge bg-warning text-dark align-self-center">Pending</span>
                                        <?php endif; ?>

                                        <!-- Optionally view booking details -->
                                        <a href="booking_view.php?id=<?php echo urlencode($b['booking_id']); ?>" class="btn btn-sm btn-outline-secondary ms-auto">Details</a>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <!-- Map -->
<div class="container mb-5">
    <div id="driverMap" style="height:500px; border-radius:12px;"></div>
</div>



<!-- Booking Modal -->
<div class="modal fade" id="bookingModal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content p-3">
      <div class="modal-header">
        <h5 class="modal-title">Book a Slot</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <input type="hidden" id="modal_station_id">
        <div class="mb-3">
            <label>Date:</label>
            <input type="date" id="visit_date" class="form-control" required>
        </div>
        <div class="mb-3">
            <label>Time:</label>
            <input type="text" id="visit_time" class="form-control" placeholder="Select Time" required readonly>
        </div>

        <div id="slotMessage" class="small text-danger mb-2"></div>
      </div>
      <div class="modal-footer">
        <button id="confirmBooking" class="btn btn-brand">Book Slot</button>
      </div>
    </div>
  </div>
</div>

<!-- Leaflet + Routing + Axios -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<script>
const ALL_STATIONS = <?php echo $stations_json; ?>;
let driverMap = null;
let markers = L.layerGroup();
let routingControl = null;
let userMarker = null;
let radiusCircle = null;
let lastMapState = { center: [20.5937, 78.9629], zoom: 5 };

// Initialize map
function initDriverMap(){
    driverMap = L.map('driverMap').setView(lastMapState.center, lastMapState.zoom);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; OpenStreetMap contributors'
    }).addTo(driverMap);
    driverMap.addLayer(markers);
    driverMap.on('moveend', () => {
        lastMapState.center = driverMap.getCenter();
        lastMapState.zoom = driverMap.getZoom();
    });
}

// Distance function (km)
function getDistanceFromLatLon(lat1, lon1, lat2, lon2) {
    const R = 6371;
    const dLat = (lat2-lat1) * Math.PI/180;
    const dLon = (lon2-lon1) * Math.PI/180;
    const a = Math.sin(dLat/2)**2 + Math.cos(lat1*Math.PI/180) * Math.cos(lat2*Math.PI/180) * Math.sin(dLon/2)**2;
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    return R * c;
}

// Plot markers and cards
function plotMarkers(stations){
    markers.clearLayers();
    const container = document.getElementById('stationCards');
    container.innerHTML = '';

    stations.forEach(station=>{
        const lat = parseFloat(station.latitude);
        const lng = parseFloat(station.longitude);
        if(lat && lng){
            L.marker([lat,lng]).addTo(markers)
                .bindPopup(`<strong>${station.station_name}</strong><br>${station.address}<br>Plug: ${station.plug_type} | Speed: ${station.charging_speed}<br>Price: ₹${station.pricing}/kWh`);

            const cardHTML = `
            <div class="col-lg-6 col-md-12 mb-4 station-card" 
                 data-name="${(station.station_name||'').toLowerCase()}" 
                 data-address="${(station.address||'').toLowerCase()}"
                 data-plug="${(station.plug_type||'').toLowerCase()}"
                 data-speed="${(station.charging_speed||'').toLowerCase()}"
                 data-price="${station.pricing}">
                <div class="card glass h-100 p-3 hover-shadow">
                    <h5 class="fw-bold">${station.station_name}</h5>
                    <p>${station.address}</p>
                    <p><strong>Plug:</strong> ${station.plug_type}</p>
                    <p><strong>Speed:</strong> ${station.charging_speed}</p>
                    <p><strong>Price:</strong> ₹${station.pricing}/kWh</p>

                    <button class="btn btn-brand mt-2 book-btn" data-id="${station.station_id}">Book Slot</button>
                    <button class="btn btn-brand mt-2 route-btn" data-lat="${lat}" data-lng="${lng}">Route & Info</button>
                    <p class="mt-2 small distance-time"></p>

                    <!-- Feedback section -->
                    <hr>
                    <div class="feedback-section mt-2">
                        <label class="small fw-semibold text-muted">Your Feedback:</label>
                        <textarea class="form-control mb-2 feedback-text" rows="2" placeholder="Write your feedback here..."></textarea>
                        <label class="small fw-semibold text-muted">Rating:</label>
<select class="form-select mb-2 feedback-rating">
    <option value="">Select rating</option>
    <option value="1">⭐ 1</option>
    <option value="2">⭐ 2</option>
    <option value="3">⭐ 3</option>
    <option value="4">⭐ 4</option>
    <option value="5">⭐ 5</option>
</select>

                        <button class="btn btn-sm btn-outline-primary submit-feedback" data-station="${station.station_id}">
                            <i class="bi bi-send"></i> Submit
                        </button>
                        <small class="feedback-msg text-success d-none mt-1">Thank you for your feedback!</small>
                    </div>
                </div>
            </div>`;
            container.insertAdjacentHTML('beforeend', cardHTML);
        }
    });

    // Route buttons
    document.querySelectorAll('.route-btn').forEach(btn=>{
        btn.addEventListener('click', ()=>{
            routeToStation(parseFloat(btn.dataset.lat), parseFloat(btn.dataset.lng), btn);
        });
    });

    // Book buttons
    document.querySelectorAll('.book-btn').forEach(btn=>{
        btn.addEventListener('click', ()=>{
            const stationId = btn.dataset.id;
            document.getElementById('modal_station_id').value = stationId;
            document.getElementById('visit_time').value = '';
            document.getElementById('slotMessage').textContent = '';
            const today = new Date().toISOString().split('T')[0];
            document.getElementById('visit_date').value = today;
            fetchAvailableSlots(stationId, today);
            new bootstrap.Modal(document.getElementById('bookingModal')).show();
        });
    });

    // Feedback submission
    // Feedback submission with rating
document.querySelectorAll('.submit-feedback').forEach(btn=>{
    btn.addEventListener('click', async ()=>{
        const stationId = btn.dataset.station;
        const section = btn.closest('.feedback-section');
        const textarea = section.querySelector('.feedback-text');
        const ratingSelect = section.querySelector('.feedback-rating');
        const msgBox = section.querySelector('.feedback-msg');

        const feedbackText = textarea.value.trim();
        const rating = ratingSelect.value;

        if(!feedbackText || !rating){ 
            alert('Please enter feedback and select a rating before submitting.'); 
            return; 
        }

        try {
            const res = await axios.post('api/save_feedback.php', {
                station_id: stationId,
                feedback: feedbackText,
                rating: rating
            }, { headers: { 'Content-Type': 'application/json' } });

            if(res.data.success){
                textarea.value = '';
                ratingSelect.value = '';
                msgBox.classList.remove('d-none');
                setTimeout(()=> msgBox.classList.add('d-none'), 2000);
            } else {
                alert(res.data.message || 'Could not save feedback.');
            }
        } catch (err){
            console.error(err);
            alert('Server error while saving feedback.');
        }
    });
});
}


// Fetch available slots
let timePicker = null;
function fetchAvailableSlots(stationId, date){
    axios.get(`api/get_slot.php?station_id=${stationId}&date=${date}`)
    .then(res=>{
        const times = res.data
            .filter(slot => String(slot.is_available).toLowerCase() === 'yes')
            .map(slot => slot.slot_time);

        if(times.length){
            document.getElementById('slotMessage').textContent = '';
            if(timePicker) timePicker.destroy();

            timePicker = flatpickr("#visit_time", {
                enableTime: true,
                noCalendar: true,
                dateFormat: "H:i",
                time_24hr: true,
                enable: times,
                defaultHour: parseInt(times[0].split(":")[0]),
                defaultMinute: parseInt(times[0].split(":")[1])
            });

        } else {
            document.getElementById('slotMessage').textContent = 'No available slots for this date.';
            if(timePicker) timePicker.clear();
        }
    })
    .catch(err=>{
        console.error(err);
        document.getElementById('slotMessage').textContent = 'Failed to fetch slots.';
        if(timePicker) timePicker.clear();
    });
}

// Confirm booking
document.getElementById('confirmBooking').addEventListener('click', async () => {
    const stationId = document.getElementById('modal_station_id').value;
    const visitDate = document.getElementById('visit_date').value;
    const visitTime = document.getElementById('visit_time').value;
    if (!visitTime) { alert('Please select a slot'); return; }

    try {
        const res = await axios.post('api/book_slot.php', {
            station_id: stationId,
            visit_date: visitDate,
            visit_time: visitTime
        }, {
            headers: { 'Content-Type': 'application/json' }
        });

        if (res.data?.message) alert(res.data.message);
        if (res.data?.success) {
            bootstrap.Modal.getInstance(document.getElementById('bookingModal')).hide();
            setTimeout(() => location.reload(), 800);
        }
    } catch (err) {
        console.error(err);
        alert('Server error: ' + (err.response?.data?.message || err.message));
    }
});



// Update slots when date changes
document.getElementById('visit_date').addEventListener('change', ()=>{
    const stationId = document.getElementById('modal_station_id').value;
    const date = document.getElementById('visit_date').value;
    fetchAvailableSlots(stationId, date);
});

// 🔎 Apply filters
document.getElementById('applyFilters').addEventListener('click', ()=>{
    const query = document.getElementById('searchStation').value.toLowerCase();
    const plug = document.getElementById('filterPlug').value.toLowerCase();
    const speed = document.getElementById('filterSpeed').value.toLowerCase();
    const price = parseFloat(document.getElementById('filterPrice').value);

    document.querySelectorAll('.station-card').forEach(card=>{
        const name = card.dataset.name || '';
        const address = card.dataset.address || '';
        const cardPlug = card.dataset.plug || '';
        const cardSpeed = card.dataset.speed || '';
        const cardPrice = parseFloat(card.dataset.price || '0');

        let match = true;
        if(query && !(name.includes(query) || address.includes(query))) match = false;
        if(plug && cardPlug !== plug) match = false;
        if(speed && cardSpeed !== speed) match = false;
        if(!isNaN(price) && cardPrice > price) match = false;

        card.style.display = match ? 'block' : 'none';
    });
});

// Initialize
document.addEventListener('DOMContentLoaded', ()=>{
    initDriverMap();
    plotMarkers(ALL_STATIONS);
});

// ROUTING / LOCATION
let watchId = null;
document.getElementById('locateBtn').addEventListener('click', ()=>{
    if(navigator.geolocation){
        if(watchId) navigator.geolocation.clearWatch(watchId);
        watchId = navigator.geolocation.watchPosition(pos=>{
            const lat = pos.coords.latitude;
            const lng = pos.coords.longitude;
            driverMap.setView([lat,lng], 13);
            if(userMarker) userMarker.setLatLng([lat,lng]);
            else {
                userMarker = L.marker([lat,lng], {icon: L.icon({iconUrl: 'https://cdn-icons-png.flaticon.com/512/684/684908.png', iconSize: [30,30]})})
                            .addTo(driverMap).bindPopup("Your Location").openPopup();
            }
            if(radiusCircle) radiusCircle.setLatLng([lat,lng]);
            else radiusCircle = L.circle([lat,lng], {radius:15000, color:'#4CAF50', fillColor:'#4CAF5022', fillOpacity:0.2}).addTo(driverMap);
            updateNearbyStations(lat,lng);
            document.getElementById('clearLocationBtn').style.display = 'inline-block';
            if(routingControl){
                const waypoints = routingControl.getWaypoints();
                if(waypoints.length >= 2) routingControl.spliceWaypoints(0,1,L.latLng(lat,lng));
            }
        }, ()=> alert('Could not get your location'), { enableHighAccuracy:true, maximumAge:0, timeout:5000 });
    } else alert('Geolocation not supported');
});

function updateNearbyStations(lat,lng){
    const nearby = ALL_STATIONS.filter(station=>{
        const d = getDistanceFromLatLon(lat,lng, parseFloat(station.latitude), parseFloat(station.longitude));
        return d <= 15;
    });
    plotMarkers(nearby);
}

// 🧭 Clear location filtering
document.getElementById('clearLocationBtn').addEventListener('click', ()=>{
    plotMarkers(ALL_STATIONS);
    if(radiusCircle){ driverMap.removeLayer(radiusCircle); radiusCircle = null; }
    document.getElementById('clearLocationBtn').style.display = 'none';
    driverMap.setView(lastMapState.center, lastMapState.zoom);
});

function routeToStation(destLat,destLng,button){
    if(!userMarker){ alert('Locate yourself first!'); return; }
    const startLat = userMarker.getLatLng().lat;
    const startLng = userMarker.getLatLng().lng;
    if(routingControl){ driverMap.removeControl(routingControl); routingControl=null; button.textContent='Route & Info'; return; }
    routingControl = L.Routing.control({
        waypoints: [L.latLng(startLat,startLng), L.latLng(destLat,destLng)],
        routeWhileDragging: true,
        fitSelectedRoutes: true,
        lineOptions: { styles: [{color: '#4CAF50', weight:5}] },
        createMarker: ()=>null,
        router: L.Routing.osrmv1({ serviceUrl: 'https://router.project-osrm.org/route/v1' })
    }).addTo(driverMap);
    routingControl.on('routesfound', e=>{
        const route = e.routes[0];
        const distanceKm = (route.summary.totalDistance/1000).toFixed(2);
        const timeMin = Math.ceil(route.summary.totalTime/60);
        // Find nearest sibling .distance-time element after the button
        const parentCard = button.closest('.card');
        const distanceEl = parentCard ? parentCard.querySelector('.distance-time') : null;
        if (distanceEl) distanceEl.textContent = `Distance: ${distanceKm} km | ETA: ${timeMin} min`;
    });
}
</script>

<?php include 'partials/footer.php'; ?>
